export const tableDropdownData =
    [
        { id: 'system_fields', label: 'System Fields',column1:'System Fields-C1',column2:'System Fields-C2' },
        { id: 'copy', label: 'Copy',column1:'Copy-C1',column2:'Copy-C2' },
        { id: 'current', label: 'Current',column1:'Current-C1',column2:'Current-C2' },
        { id: 'edit', label: 'Edit',column1:'Edit-C1',column2:'Edit-C2' },
        { id: 'state', label: 'State',column1:'State-C1',column2:'State-C2' },
        { id: 'data_fields', label: 'Data Fields',column1:'Data Fields-C1',column2:'Data Fields-C2' },
        { id: 'date', label: 'Date',column1:'Date-C1',column2:'Date-C2' },
        { id: 'user', label: 'User',column1:'User-C1',column2:'User-C2' },
        { id: 'version', label: 'Version',column1:'Version-C1',column2:'Version-C2' },
        { id: 'division', label: 'Division',column1:'Division-C1',column2:'Division-C2' },
        { id: 'delete', label: 'Delete',column1:'Delete-C1',column2:'Delete-C2' },
        { id: 'division-1', label: 'Devision-1',column1:'Devision-1-C1',column2:'Devision-1-C2' },
        { id: 'input', label: 'Input',column1:'Input-C1',column2:'Input-C2' },
        { id: 'division-2', label: 'Devision-2',column1:'Devision-2-C1',column2:'Devision-2-C2' },
        { id: 'brand', label: 'Brand',column1:'Brand-C1',column2:'Brand-C2' },
        { id: 'description', label: 'Description',column1:'Description-C1',column2:'Description-C2' },
        { id: 'category', label: 'Category',column1:'Category-C1',column2:'Category-C2' },
        { id: 'subcat-1', label: 'SubCat-1',column1:'SubCat-1-C1',column2:'SubCat-1-C2' },
        { id: 'visual', label: 'Visual',column1:'Visual-C1',column2:'Visual-C2' },
        { id: 'description', label: 'Description',column1:'Description-C1',column2:'Description-C2' },       
    ]